In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline



In [3]:
data = pd.read_excel('food.xlsx')
data.head()


Food_ID                  Name   Taste  Cuisine  Veg_Non  Rating
0        1   summer squash salad   sweet  Western      veg       6
1        2  chicken minced salad   umami   Indian  non-veg       3
2        3  sweet chilli almonds  savory   Indian      veg      10
3        4       tricolour salad  savory   Indian      veg       2
4        5        christmas cake   sweet  English      veg       4

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Food_ID  400 non-null    int64 
 1   Name     400 non-null    object
 2   Taste    400 non-null    object
 3   Cuisine  400 non-null    object
 4   Veg_Non  400 non-null    object
 5   Rating   400 non-null    int64 
dtypes: int64(2), object(4)
memory usage: 18.9+ KB


In [5]:
data.Cuisine.unique()

array(['Western', 'Indian', 'English', 'Japanese', 'Italian', 'Mexican',
       'Thai', 'French', 'Chinese', 'Turkish', 'Swedish', 'German',
       'Spanish', 'Korean', 'Vietnames', 'Nepalese'], dtype=object)

In [6]:
data.head()

Food_ID                  Name   Taste  Cuisine  Veg_Non  Rating
0        1   summer squash salad   sweet  Western      veg       6
1        2  chicken minced salad   umami   Indian  non-veg       3
2        3  sweet chilli almonds  savory   Indian      veg      10
3        4       tricolour salad  savory   Indian      veg       2
4        5        christmas cake   sweet  English      veg       4

In [7]:
data['Food_ID']

0        1
1        2
2        3
3        4
4        5
      ... 
395    396
396    397
397    398
398    399
399    400
Name: Food_ID, Length: 400, dtype: int64

In [8]:
new_cols = ['Name', 'Taste', 'Cuisine','Veg_Non','Rating']
df = data[new_cols]
df.head()

Name   Taste  Cuisine  Veg_Non  Rating
0   summer squash salad   sweet  Western      veg       6
1  chicken minced salad   umami   Indian  non-veg       3
2  sweet chilli almonds  savory   Indian      veg      10
3       tricolour salad  savory   Indian      veg       2
4        christmas cake   sweet  English      veg       4

In [9]:
!pip install kmodes

In [10]:
from kmodes.kmodes import KModes

In [11]:
k1 = 6
km = KModes(n_clusters=k1, n_init=400,verbose=1)
clusters1 = km.fit_predict(df)


Initialization method and algorithm are deterministic. Setting n_init to 1.
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 60, cost: 1055.0
Run 1, iteration: 2/100, moves: 28, cost: 1045.0
Run 1, iteration: 3/100, moves: 20, cost: 1045.0


In [12]:
user_food = ['summer squash salad','sweet','Western','veg' ,'6']

distances1 = np.sum(km.cluster_centroids_ != user_food, axis=1)
nearest_indices = np.argsort(distances1)[:10]
nearest_points = df.iloc[nearest_indices].sort_values('Rating', ascending=False)['Name']


print(nearest_points)
print(distances1)

2                         sweet chilli almonds
5    japanese curry arancini with barley salsa
0                          summer squash salad
4                               christmas cake
1                         chicken minced salad
3                              tricolour salad
Name: Name, dtype: object
[4 2 5 5 2 3]


In [13]:
user_food2 = ['khichdi','spicy','Indian','veg','10']
distances2 = np.sum(km.cluster_centroids_ != user_food2, axis=1)
print(distances2)
nearest_indices2 = np.argsort(distances2)[:10]
print(nearest_indices2)
nearest_points2 = df.iloc[nearest_indices2].sort_values('Rating', ascending=False)['Name']

print(nearest_points2)

[3 4 4 3 4 4]
[0 3 1 2 4 5]
2                         sweet chilli almonds
5    japanese curry arancini with barley salsa
0                          summer squash salad
4                               christmas cake
1                         chicken minced salad
3                              tricolour salad
Name: Name, dtype: object


In [15]:
user_food3 = [['filo pizza','savory','Italian','veg','1']]
distances3 = np.sum(km.cluster_centroids_ != user_food3, axis=1)
print(distances3)
print('\n')
nearest_indices3 = np.argsort(distances3)[:10]
print("argsort values", np.argsort(distances3))

print(nearest_indices3)
nearest_points3 = df.iloc[nearest_indices3].sort_values('Rating', ascending=False)['Name']

print(nearest_points3)

[3 3 5 5 4 3]


argsort values [0 1 5 4 2 3]
[0 1 5 4 2 3]
2                         sweet chilli almonds
5    japanese curry arancini with barley salsa
0                          summer squash salad
4                               christmas cake
1                         chicken minced salad
3                              tricolour salad
Name: Name, dtype: object


In [19]:
import numpy as np
from kmodes.kmodes import KModes

k1 = 6
km = KModes(n_clusters=k1, n_init=400, verbose=1)
clusters1 = km.fit_predict(df)

user_food3 = ['filo pizza', 'savory', 'Italian', 'veg', '1']
distances3 = np.sum(df != user_food3, axis=1)  # Calculate dissimilarity with each data point
nearest_indices3 = np.argsort(distances3)[:10]
nearest_points3 = df.iloc[nearest_indices3]
nearest_points3 = nearest_points3.sort_values(by='Rating',ascending=False)

print(nearest_points3)

Initialization method and algorithm are deterministic. Setting n_init to 1.
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 60, cost: 1055.0
Run 1, iteration: 2/100, moves: 28, cost: 1045.0
Run 1, iteration: 3/100, moves: 20, cost: 1045.0
                                       Name   Taste  Cuisine Veg_Non  Rating
286                   pasta in cheese sauce  savory  Italian     veg       8
183                    vegetable bruschetta  savory  Italian     veg       8
263                        kuttu atta pizza  savory  Italian     veg       5
379  Parmesan Cauliflower and Parsley Salad  savory  Italian     veg       5
356                         Parmesan Toasts  savory  Italian     veg       4
335                        Potato Casserole  savory  Italian     veg       3
60   crunchy vegetable dal sattu croquettes  savory  Italian     veg       3
54                               filo pizza  savory  Italian     veg       1
48  

In [33]:
def giveRecommendation(food):
    distance = np.sum(df != food, axis=1)
    nearest_indices = np.argsort(distance)[:10]
    nearest_points = df.iloc[nearest_indices]
    nearest_points = nearest_points.sort_values(by='Rating',ascending=False)
    food_rec = nearest_points['Name'].tolist()
    print("Here are your top 10 recommendations for ",food[0])
    for i in range(0,len(food_rec)):
        print("{}. {}".format(i+1,food_rec[i]))

In [34]:
# example working of the recommendation system
user_food4 = ['Parmesan Toasts','savory','Italian','veg','5']
giveRecommendation(user_food4)

Here are your top 10 recommendations for  Parmesan Toasts
1. pasta in cheese sauce
2. vegetable bruschetta
3. kuttu atta pizza
4. Parmesan Cauliflower and Parsley Salad
5. Parmesan Toasts
6. Potato Casserole
7. crunchy vegetable dal sattu croquettes
8. christmas tree pizza
9. filo pizza
10. Pasta with Garlic-Scape Pesto
